### ISSUE TITLE
Issue logged on micro editor 

### ISSUE THREAD

**Issue by tommyshem** [NicolaiSoeborg/filemanager-plugin#14]
Issue logged on micro editor.
zyedidia/micro#926

**Comment by sum01** [comment]
A possible solution to the off-screen list of files (after opening something at the bottom of a long list) would be to put this in `refreshTree()`
```lua
local cur_view = CurView()
if cur_view == treeView then
  -- Just put the cursor on the ".." every refresh
  cur_view.Buf.Cursor:Goto(2)
end
```
I haven't tried it, but I assume it would do what I expect, by what I've read in `micro/cursor.go`

**Comment by sum01** [comment]
Fixed the out-of-bounds bug mentioned in that issue post [in my WIP branch](https://github.com/sum01/filemanager-plugin/tree/fixes_and_more) in [this commit](https://github.com/sum01/filemanager-plugin/commit/5daa98fbb2656b6d97d720ee2cfa9a11196810ce)

This branch is mostly done, but there's a weird issue with mousedown moving down 2 positions instead of 1.

**Comment by tommyshem** [comment]
@sum01 I tested the above and it does not solve to problem.
Below code put in the end of refreshTree() seems to work (still testing, but looks good)  
```lua
     treeView:CursorStart(false)
     treeView:Relocate()
     treeView:CursorDown(true)
```
Still have to sort out
* [ ] page-up as it goes to the first line which is the path name.
* [ ] Search in the file tree also needs sorting as it could still pick up the path name.
* [ ] Readonly view still needs sorting out as this could cause problems.
* [ ] Check other key combos might be a problem.

**Comment by sum01** [comment]
Hmm. Guess you're right about it not being fixed. Got that index out of range thing opening `/usr/lib`

This fixed page-up/down for me though https://github.com/sum01/filemanager-plugin/commit/fea75ec27c3130e68e1773e31701222f0e73677e also works on Ctrl+up/down

**Comment by sum01** [comment]
So doing
```lua
    for i = 1, #list do
      treeView.Buf:Insert(Loc(0, i - 1), list[i] .. "\n")
    end
```
instead of https://github.com/sum01/filemanager-plugin/blob/fixes_and_more/filemanager.lua#L73-L77 fixed the out-of-bounds when opening `/usr/lib` for me. I figured inserting everything at once was the issue, and I seem to be right?

Just needs something to remove the last newline on the end of loop.

**Comment by sum01** [comment]
Found `ScrollUp` https://github.com/zyedidia/micro/blob/master/cmd/micro/view.go#L185 for the issue with stuff being off-screen.

**Comment by sum01** [comment]
Fixed the cursor being off the screen here https://github.com/sum01/filemanager-plugin/commit/164f441f1d1432302459fce6dca21727a095905e

It will auto-scroll up/down based on where your cursor is, and when you go to a new directory, it will put the cursor on the `..`
